services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - "8081:80"
    depends_on:
      - backend
    networks:
    - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DOMAIN_NAME: localhost
      QUARKUS_DATASOURCE_REACTIVE_URL: mysql://database:3306/safilo
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: test
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /app/priv.pem
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: /app/pub.pem
      MP_JWT_VERIFY_PUBLICKEY_ALGORITHM: RS256
      MP_JWT_VERIFY_ISSUER: https://localhost:8080
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: create
      QUARKUS_MAILER_HOST: mailhog
      QUARKUS_MAILER_PORT: 1025
      QUARKUS_MAILER_FROM: cdr@gmail.com
      CDR_EMAILS: cdr@gmail.com
      CDR_CANCEL_EMAILS: cdr@gmail.com
      # Fema
      QUARKUS_REST_CLIENT_FEMA_EXPEDITIONS_URL: http://fema-mock:9091/FemaMock
      QUARKUS_SCHEDULER_CRON_TYPE: unix
      FEMA_REPORT_CRON: "00 19 * * 1-5"
      FEMA_REPORT_EMAILS: reports-safilo@test.com
      FEMA_USERNAME: TESTUSER
      FEMA_PASSWORD: TESTPASS
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - app-network

  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: safilo
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptest"]
      interval: 5s
      retries: 10
      start_period: 15s
  mailhog:
    image: mailhog/mailhog
    ports:
     - "8025:8025"
    networks:
     - app-network
  fema-mock:
    build:
      context: ./mock-fema
      dockerfile: Dockerfile
    networks:
      - app-network
networks:
  app-network:

volumes:
    db_data:
