- hosts: all
  tasks:
    - name: Ensure backend folder exists
      become: yes
      file:
        path: /safilo/backend
        group: backend
        owner: safilo
        mode: 0775
        recurse: yes
        state: directory

    - name: Ensure frontend folder exists
      become: yes
      file:
        path: /var/www/safilo
        group: www-data
        owner: www-data
        mode: 0775
        recurse: yes
        state: directory

    - name: Ensure frontend images folder exists
      become: yes
      file:
        path: /var/www/safilo-images
        group: www-data
        owner: www-data
        mode: 0775
        recurse: yes
        state: directory

    - name: Create OpenSSL JWT signing key
      become: yes
      openssl_privatekey:
        size: 8192
        owner: safilo
        group: backend
        mode: 0600
        type: RSA
        path: /safilo/priv.pem

    - name: Transfer new backend to the server
      copy:
        src: backend/
        dest: /safilo/backend
      register: backend

    - name: Transfer new frontend to the server
      copy:
        src: frontend/
        dest: /var/www/safilo

    - name: Copy systemd service
      become: yes
      template:
        src: safilo.service
        dest: /etc/systemd/system
      register: safilo_service

    - name: Start backend service
      become: yes
      systemd:
        name: safilo
        state: restarted
        enabled: yes
        daemon-reload: yes
      when: safilo_service.changed or backend.changed
