# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 8080, host: 8889

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "4"
    vb.memory = "2048"
  end

  config.vm.provider "libvirt" do |lv|
    lv.cpus = "4"
    lv.memory = "2048"
  end
end

