---

- name: restart backend
  become: yes
  systemd:
    name: safilo
    state: restarted

- name: restart frontend
  become: yes
  systemd:
    name: caddy
    state: restarted
  notify: restart backend
