---

- name: restart backend
  become: yes
  systemd:
    name: safilo
    state: restarted
    daemon-reload: true

- name: restart frontend
  become: yes
  systemd:
    name: caddy
    state: restarted
  notify: restart backend

- name: restart proxy
  become: yes
  systemd:
    name: fema-proxy
    state: restarted
