site_name: Plataforma Casa dos Reclamos
site_url: https://dmaxter.gitlab.io/cdr-safilo/
docs_dir: content/
nav:
  - Início: index.md
  - Safilo: safilo.md
  - CDR: cdr.md
  #- Utilizadores: users.md
  - Detalhes Técnicos: technical.md
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Mudar para modo noturno

    # Palette toggle for dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Mudar para modo diurno
markdown_extensions:
  - tables
  - toc:
      permalink: 🔗
