name: Deploy application

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**
      - deploy/**
      - .github/workflows/deploy.yml
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest

    env:
      DOMAIN_NAME: ${{ vars.HOST }}

      QUARKUS_DATASOURCE_JDBC: false

      QUARKUS_HTTP_AUTH_PROACTIVE: false
      QUARKUS_SECURITY_SECURITY_PROVIDERS: BC

      MP_JWT_TOKEN_HEADER: Cookie
      MP_JWT_TOKEN_COOKIE: identity
      SMALLRYE_JWT_PATH_GROUPS: roles
      MP_JWT_VERIFY_ISSUER: https://${[ vars.HOST }}:8080
      MP_JWT_VERIFY_PUBLICKEY_ALGORITHM: RS256
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: /safilo/pub.pem
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /safilo/priv.pem

      QUARKUS_SCHEDULER_CRON_TYPE: unix

    steps:
      - name: "Download repository"
        uses: actions/checkout@v4

      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          cache: "gradle"
          distribution: "zulu"
          java-version: "17"

      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "Build backend"
        run: |
          cd backend
          ./gradlew quarkusBuild

      - name: "Publish backend artifact"
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend/build/quarkus-app

      - name: "Publish ansible artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: ansible
          path: deploy

  build_frontend:
    runs-on: ubuntu-latest

    env:
      VUE_APP_ROOT_API: https://${{ vars.HOST }}:8889
      VUE_APP_NAME: Casa dos Reclamos

    steps:
      - name: "Download repository"
        uses: actions/checkout@v4

      - name: "Set up Node.JS 18"
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: "Build frontend"
        run: |
          cd frontend
          yarn install
          yarn run build

      - name: "Publish frontend"
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist

  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: "Download repository"
        uses: actions/checkout@v4

      - name: "Publish proxy artifact"
        uses: actions/upload-artifact@v4
        with:
          name: proxy
          path: proxy.py

  deploy_application:
    runs-on: ubuntu-latest
    env:
      DOMAIN_NAME: ${{ vars.HOST }}
      CDR_EMAILS: ${{ vars.CDR_MAILS }}
      CANCEL_EMAILS: ${{ vars.CANCEL_EMAILS }}

      BACKEND: backend/
      FRONTEND: frontend/
      PROXY: proxy.py

      QUARKUS_HTTP_SSL_CERTIFICATE_FILE: ${{ secrets.SSL_CERT }}
      QUARKUS_HTTP_SSL_CERTIFICATE_KEY_FILE: ${{ secrets.SSL_KEY }}
      QUARKUS_HTTP_CORS: true
      QUARKUS_HTTP_CORS_ORIGINS: https://${{ vars.HOST }}
      QUARKUS_HTTP_CORS_METHODS: GET,PUT,POST,DELETE
      QUARKUS_HTTP_BODY_UPLOADS_DIRECTORY: ${{ vars.IMAGE_DIR }}

      QUARKUS_DATASOURCE_REACTIVE_URL: mysql://${{ vars.MYSQL_HOST }}:3306/${{ vars.DB_NAME }}
      QUARKUS_DATASOURCE_USERNAME: ${{ secrets.MYSQL_USER }}
      QUARKUS_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASS }}

      QUARKUS_MAILER_HOST: ${{ vars.SMTP_HOST }}
      QUARKUS_MAILER_PORT: ${{ vars.SMTP_PORT }}
      QUARKUS_MAILER_USERNAME: ${{ vars.SMTP_MAIL }}
      QUARKUS_MAILER_PASSWORD: ${{ secrets.SMTP_PASS }}
      QUARKUS_MAILER_FROM: ${{ vars.SMTP_MAIL }}

      FEMA_USERNAME: ${{ secrets.FEMA_USERNAME }}
      FEMA_PASSWORD: ${{ secrets.FEMA_PASSWORD }}
      FEMA_REPORT_CRON: "00 19 * * 1-5"
      FEMA_REPORT_EMAILS: ${{ vars.FEMA_REPORT_EMAILS }}
      FEMA_EXPEDITIONS_URL: ${{ vars.FEMA_EXPEDITIONS_URL }}
      FEMA_EXPEDITIONS_PROXY: "127.0.0.1:9000"
    needs:
      - build_backend
      - build_frontend
      - proxy
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Move artifacts to ansible folder
        run: |
          mkdir ansible/files
          mv {backend,frontend,proxy/proxy.py} ansible/files

      - name: Run ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          key: ${{ secrets.SSH_KEY }}
          inventory: |
            safilo ansible_host=${{ secrets.HOST }} ansible_user=${{ secrets.SSH_USER }} ansible_port=${{ secrets.SSH_PORT }}
