name: Deploy application

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: "Download repository"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          cache: "gradle"
          distribution: "zulu"
          java-version: "17"

      - name: "Set up Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Build backend"
        run: |
          cd backend
          ./gradlew quarkusBuild

      - name: "Publish backend artifact"
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: backend/build/quarkus-app

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Node.JS 16"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: "Build frontend"
        run: |
          cd frontend
          yarn install
          yarn run serve

      - name: "Publish frontend"
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend/dist
