name: Publish documentation

on:
  push:
    branches:
      - main
    paths:
      - docs/**/*
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and Material for MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build -f docs/mkdocs.yml

      - name: Publish Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "docs/site/"

  deploy_documentation:
    runs-on: ubuntu-latest

    needs: build_documentation

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v2
